### ISSUE TITLE
released version failed to display

### ISSUE THREAD

**Issue by yangzetao** [Korpyc/circular_color_picker#1]
Under debug mode, the color picker works well.
However, for the Android released version (tested with Nexus 6, android 7.1), the color picker disapears.

The windows' released version no issue.

**Comment by Korpyc** [comment]
@yangzetao could you provide an example of code?

**Comment by yangzetao** [comment]
I uploaded source code to google drive for your reference (was tested and confirmed release version missing the color-picker, but debug version works well):
https://drive.google.com/file/d/1JNJ_o70TGMtuYwDeCu22AmLkPAgzTcq8/view?usp=sharing

Right now I am using vscode + Flutter 2.8.0-3.3pre (latest).
Thanks.

**Comment by Korpyc** [comment]
@yangzetao thank you for your feadback!
To fix it, remove "shadows: []," line, or write your custom shadow.
Shadows could be null, but couldn't be empty list.
I will make changes to allow write null to shadows further.

**Comment by yangzetao** [comment]
Thank you very much.
